config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :login
    post 'login' => 'sessions#create'
    delete 'logout' => 'devise/sessions#destroy', :as => :logout

    get 'signup' => 'devise/registrations#new', :as => :signup
    post 'signup' => 'registrations#create'
  end

  root 'static_pages#home'

  get '/info' => 'static_pages#info'
  get '/calculator' => 'static_pages#calculator'
  post '/save_result_in_cookies' => 'static_pages#save_result_in_cookies'

  resources :users, only: [:get, :post] do
    get '/results', to: 'results#index'
    post '/results', to: 'results#create'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- to load script in specific pages -->
    <%= yield(:script) %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="<%= image_url('goccia.ico') %>" />
    <title><%= yield(:title) %> - Water Footprint</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript">
      /* cookie consent message, source from silktide.com */
      window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website.","dismiss":"OK","learnMore":"More info","link":"","theme":"dark-bottom"};
    </script>

</head>

<body>

  <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Water Footprint</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= "active" if current_page?(root_path) %>"><a href="<%= root_path %>">Home</a></li>
            <li class="<%= "active" if current_page?(info_path) %>"><a href="<%= info_path %>">Info</a></li>
            <li><a href="http://www.fbk.eu/about-us" target="_blank">About</a></li>
            <li class="<%= "active" if current_page? calculator_path %>">
              <a href="<%= calculator_path %>">Calculator</a>
            </li>
            <% if signed_in? %>
            <li class="<%= "active" if current_page? user_results_path(current_user['id']) %>">
              <a href="<%= user_results_path(current_user['id']) %>">History</a>
            </li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li><a href="<%= user_results_path(current_user['id']) %>"><span><span class="fa fa-user"></span> <%= current_user['name'] %></span></a></li>
            <li><%= link_to "Logout", logout_path, :method => :delete, style:"color:#cc0000;" %></li>
          <% else %>
            <li class="<%= "active" if current_page?(signup_path) %>"><a href="<%= signup_path %>">Signup</a></li>
            <li class="<%= "active" if current_page?(login_path) %>"><a href="<%= login_path %>">Login</a></li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>



    <%= yield %>


    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                          <%= link_to "Home", root_path %>
                        </li>
                        <li class="footer-menu-divider">⋅</li>
                        <li>
                          <%= link_to "Info", info_path %>
                        </li>
                        <li class="footer-menu-divider">⋅</li>
                        <li>
                          <a href="http://www.fbk.eu/about-us" target="_blank">About</a>
                        </li>
						            <li class="footer-menu-divider">⋅</li>

                        <% if signed_in? %>
                        <li>
                          <%= link_to "Logout", logout_path %>
                        </li>
                        <% else %>
                        <li>
                          <%= link_to "Login", login_path %>
                        </li>
						            <li class="footer-menu-divider">⋅</li>
                        <li>
                          <%= link_to "Signup", signup_path %>
                        </li>
                        <% end %>
                    </ul>
                    <p class="copyright text-muted small">Copyright © FBK 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>